
export let code = "._loadingScreen_3ik70_1 {\n  min-height: var(--app-height);\n  background-color: #a3d4d2;\n  display: grid;\n  grid-template-columns: 30% 70%;\n  grid-template-rows: fit-content(0) auto auto;\n}\n._logo_3ik70_8 {\n  grid-column: 1 / span 2;\n  padding-left: 10px;\n  padding-top: 20px;\n  max-width: 100%;\n  transition: opacity 500ms ease, transform 500ms ease;\n}\n._logo_3ik70_8._hidden_3ik70_15 {\n  opacity: 0;\n  transform: translateX(-20px);\n}\n._progressBar_3ik70_19 {\n  position: relative;\n  margin: 20px auto 80px auto;\n  width: 3px;\n  background-color: #a30339;\n  color: #a30339;\n  z-index: 2;\n  transition: all 500ms ease;\n}\n._progressBar_3ik70_19._hidden_3ik70_15 {\n  opacity: 0;\n  transform: translateX(20px);\n}\n._progressBar_3ik70_19::before {\n  content: '';\n  box-sizing: border-box;\n  display: block;\n  width: 13px;\n  height: 13px;\n  margin-left: -5px;\n  margin-top: -6.5px;\n  border-radius: 6.5px;\n  background-color: #a30339;\n}\n._progressBar_3ik70_19::after {\n  content: '';\n  box-sizing: border-box;\n  display: block;\n  position: absolute;\n  bottom: -6.5px;\n  width: 13px;\n  height: 13px;\n  margin-left: -5px;\n  border-radius: 6.5px;\n  background-color: #a30339;\n}\n._progressBar_3ik70_19 div {\n  box-sizing: content-box;\n  position: absolute;\n  width: 50px;\n  height: 20px;\n  line-height: 20px;\n  margin-top: -11px;\n  margin-left: 29.5px;\n  border-radius: 11px;\n  border: 1px solid #a30339;\n  text-align: center;\n}\n._progressBar_3ik70_19 div::before {\n  content: '';\n  position: absolute;\n  display: block;\n  box-sizing: border-box;\n  width: 29px;\n  border-top: 1px dashed #a30339;\n  margin-left: -30px;\n  margin-top: 9.5px;\n}\n._progressBar_3ik70_19 div::after {\n  content: '';\n  position: absolute;\n  display: block;\n  box-sizing: border-box;\n  width: 13px;\n  height: 13px;\n  border-radius: 6.5px;\n  border: 3px solid #a30339;\n  background-color: #a3d4d2;\n  margin-left: -35px;\n  margin-top: -16px;\n}\n._animation_3ik70_90 {\n  padding: 0px 40px 60px 40px;\n  max-width: 80%;\n  justify-self: right;\n  align-self: center;\n  transition: all 500ms ease;\n}\n._animation_3ik70_90._hidden_3ik70_15 {\n  opacity: 0;\n}\n._dottedBackground_3ik70_100 {\n  grid-column: 1 / span 2;\n  transition: opacity 500ms ease;\n}\n._dottedBackground_3ik70_100._hidden_3ik70_15 {\n  opacity: 0;\n}\n._dottedBackground_3ik70_100 div {\n  transform: translateY(-50%);\n  transition: transform 500ms ease;\n  max-height: 40px;\n}\n._dottedBackground_3ik70_100 div._hidden_3ik70_15 {\n  transform: translateY(0);\n}\n";
let json = {"loadingScreen":"_loadingScreen_3ik70_1","logo":"_logo_3ik70_8","hidden":"_hidden_3ik70_15","progressBar":"_progressBar_3ik70_19","animation":"_animation_3ik70_90","dottedBackground":"_dottedBackground_3ik70_100"};
export default json;

// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';

  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}